name: Translate Posts

on:
  push:
    branches:
      - main
    paths:
      - '_posts/**/*'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests pyyaml
      - name: Translate missing posts
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Get all files in _posts directory
          POST_FILES=$(find _posts -name "*.md" -print)

          # Loop through each post file
          for INPUT_FILE in $POST_FILES; do
            FILENAME=$(basename "$INPUT_FILE")
            FILENAME_WITHOUT_EXT="${FILENAME%.*}"
            OUTPUT_FILE="_posts/es/$FILENAME_WITHOUT_EXT-es.md"

            # Check if translation exists
            if [ ! -f "$OUTPUT_FILE" ]; then
              echo "Translating $INPUT_FILE"
              python translate.py "$INPUT_FILE" "$OUTPUT_FILE" "$OPENROUTER_API_KEY" "google/gemini-2.0-flash-001"
            else
              echo "Translation already exists for $INPUT_FILE, skipping."
            fi
          done
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add _posts/es/*-es.md
          git commit -m "Translated missing posts to Spanish"
          git push