name: Translate Posts

on:
  push:
    paths:
      - '_posts/**/*'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests pyyaml
      - name: Check if translation already exists
        id: check_translation
        run: |
          INPUT_FILE=$(find _posts -name "*.md" -print -quit)
          FILENAME=$(basename "$INPUT_FILE")
          FILENAME_WITHOUT_EXT="${FILENAME%.*}"
          OUTPUT_FILE="_posts/es/$FILENAME_WITHOUT_EXT-es.md"
          if [ -f "$OUTPUT_FILE" ]; then
            echo "::set-output name=exists::true"
            echo "Translation already exists for $INPUT_FILE, skipping."
          else
            echo "::set-output name=exists::false"
          fi
      - name: Translate post
        if: steps.check_translation.outputs.exists == 'false'
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          INPUT_FILE=$(find _posts -name "*.md" -print -quit)
          FILENAME=$(basename "$INPUT_FILE")
          FILENAME_WITHOUT_EXT="${FILENAME%.*}"
          OUTPUT_FILE="_posts/es/$FILENAME_WITHOUT_EXT-es.md"
          python translate.py "$INPUT_FILE" "$OUTPUT_FILE" "$OPENROUTER_API_KEY" "google/gemini-2.0-flash-001"
      - name: Commit and push changes
        if: steps.check_translation.outputs.exists == 'false'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add _posts/es/*-es.md
          git commit -m "Translated post to Spanish"
          git push