name: Translate

on:
  workflow_dispatch:

jobs:
  translate_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests pyyaml
      - name: Create language directories
        run: |
          # Create language directories if they don't exist
          mkdir -p _posts/es
          mkdir -p _news/es
          mkdir -p _i18n
      - name: Translate missing posts
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Get all files in _posts directory (excluding language subdirectories)
          POST_FILES=$(find _posts -maxdepth 1 -name "*.md" -print)

          # Loop through each post file
          for INPUT_FILE in $POST_FILES; do
            FILENAME=$(basename "$INPUT_FILE")
            
            # Skip if the translated file already exists
            if [ -f "_posts/es/$FILENAME" ]; then
              echo "Skipping $FILENAME - translation already exists"
              continue
            fi

            echo "Translating $INPUT_FILE"
            python "$(pwd)/translate.py" _posts es "$OPENROUTER_API_KEY" "google/gemini-2.0-flash-001" "$INPUT_FILE"
          done
      - name: Translate missing news
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Get all files in _news directory (excluding language subdirectories)
          NEWS_FILES=$(find _news -maxdepth 1 -name "*.md" -print)

          # Loop through each news file
          for INPUT_FILE in $NEWS_FILES; do
            FILENAME=$(basename "$INPUT_FILE")
            
            # Skip if the translated file already exists
            if [ -f "_news/es/$FILENAME" ]; then
              echo "Skipping $FILENAME - translation already exists"
              continue
            fi

            echo "Translating $INPUT_FILE"
            python "$(pwd)/translate.py" _news es "$OPENROUTER_API_KEY" "google/gemini-2.0-flash-001" "$INPUT_FILE"
          done
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Add any new files including those in language subdirectories
          git add _posts/*.md _posts/es/*.md _news/*.md _news/es/*.md _i18n/*.yml

          # Check if there are any changes to commit
          if git diff --quiet --cached; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Translated missing posts and news to Spanish"
          git push