name: Translate Posts

on:
  push:
    paths:
      - '_posts/**/*'

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests pyyaml
      - name: Translate post
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(echo ${{ github.event.commits[0].modified }} | tr -d '[]' | tr -d '"' | sed 's/,/ /g')

          # Find the first markdown file in the list of changed files
          INPUT_FILE=""
          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" == *_posts/*.md ]]; then
              INPUT_FILE="$FILE"
              break
            fi
          done

          if [ -z "$INPUT_FILE" ]; then
            echo "No markdown file found in the list of changed files, skipping."
            exit 0
          fi

          FILENAME=$(basename "$INPUT_FILE")
          FILENAME_WITHOUT_EXT="${FILENAME%.*}"
          OUTPUT_FILE="_posts/es/$FILENAME_WITHOUT_EXT-es.md"
          python translate.py "$INPUT_FILE" "$OUTPUT_FILE" "$OPENROUTER_API_KEY" "gemini/gemini-2-flash"
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          mkdir -p _posts/es
          git add _posts/es/*-es.md
          git commit -m "Translated post to Spanish"
          git push